# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bluetooth-Controller' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bluetooth-Controller
 pod 'SnapKit', '~> 5.0.1'
pod 'QMUIKit', '~> 4.2.2'

end

target 'SimpleBluetooth' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleBluetooth

end
